env:
  - CGO_ENABLED=0

builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64

archives:
  - id: zip
    formats: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum

release:
  prerelease: auto
